cite_homepage:
    path:     /
    defaults: { _controller: CiteBundle:Default:indexU }

cite_homepageAdmin:
    path:     /HomeA
    defaults: { _controller: CiteBundle:Default:index }

cite_homepageMember:
    path:     /HomeM
    defaults: { _controller: CiteBundle:Default:indexM }

################################################################ Events #############################################################
EventsRead:
    path:     /HomeA/Events
    defaults: { _controller: CiteBundle:Evenement:ReadEvents }

EventsCreate:
    path:     /HomeA/Events/create
    defaults: { _controller: CiteBundle:Evenement:CreateEvent }

EventsDelete:
    path:     /HomeA/Events/delete/{id}
    defaults: { _controller: CiteBundle:Evenement:DeleteEvent }

EventsUpdate:
    path:     /HomeA/Events/update/{id}
    defaults: { _controller: CiteBundle:Evenement:UpdateEvent }

EventsSearch:
    path:   /HomeA/SearcheEvent
    defaults: { _controller: CiteBundle:Evenement:SearchEvent}



EventsReadM:
    path:     /HomeM/EventsM
    defaults: { _controller: CiteBundle:Evenement:ReadEventsM }

Event1ShowM:
    path:     /HomeM/Event1M/{idEvent}
    defaults: { _controller: CiteBundle:Evenement:Show1EventM }



EventsReadU:
    path:     /HomeU/EventsU
    defaults: { _controller: CiteBundle:Evenement:ReadEventsU }

Event1ShowU:
    path:     /HomeU/Event1U/{idEvent}
    defaults: { _controller: CiteBundle:Evenement:Show1EventU }



web_inscri:
    path: /HomeM/EventsM/Inscri/{ideve}/{iduser}
    defaults: {_controller: CiteBundle:Default:Inscri }

################################################################ History ############################################################
HistoryRead:
    path:     /HomeA/History
    defaults: { _controller: CiteBundle:History:ReadHistory }

HistoryCreate:
    path:     /HomeA/Events/{id}
    defaults: { _controller: CiteBundle:History:CreateHistory }

HistoryDelete:
    path:     /HomeA/History/delete/{id}
    defaults: { _controller: CiteBundle:History:DeleteHistory }




HistoryReadM:
    path:     /HomeM/HistoryM
    defaults: { _controller: CiteBundle:History:ReadHistoryM }

History1ShowM:
    path:     /HomeM/History1M/{idHistory}
    defaults: { _controller: CiteBundle:History:Show1HistoryM }


HistoryReadU:
    path:     /HomeU/HistoryU
    defaults: { _controller: CiteBundle:History:ReadHistoryU }

History1ShowU:
    path:     /HomeU/History1U/{idHistory}
    defaults: { _controller: CiteBundle:History:Show1HistoryU }

################################################################ Mailing ############################################################
MailSend:
    path:     /Mail/{id}
    defaults: { _controller: CiteBundle:Evenement:SendMail }

################################################################ Categorie ############################################################
CategorieRead:
    path:     /HomeA/Categorie
    defaults: { _controller: CiteBundle:Categorie:ReadCategorie }

CategorieCreate:
    path:     /HomeA/Categorie/create
    defaults: { _controller: CiteBundle:Categorie:CreateCategorie }

CategorieDelete:
    path:     /HomeA/Categorie/delete/{id}
    defaults: { _controller: CiteBundle:Categorie:DeleteCategorie }

CategorieUpdate:
    path:     /HomeA/Categorie/update/{id}
    defaults: { _controller: CiteBundle:Categorie:UpdateCategorie }

